### ISSUE TITLE
> and < symbols

### ISSUE THREAD

**Issue by winterstew** [farling42/csv2rw#65]
It appears that greater-than and less-than symbols (when not used as part of a tag) in the CSV file crashes the import.  Changing them in the CSV to the HTML symbols entities prevents the crash

The error reported by Realm Works is:
The following errors were encountered during import:
C++ Exception: Not in a span at line 1633 in file utility.cpp

[Test Import.zip](https://github.com/farling42/csv2rw/files/3285407/Test.Import.zip)

**Comment by farling42** [comment]
If the single cell in the CSV file starts with "<" and ends with ">" then the entire cell is treated as if it is HTML; thus you will have to encode any < or > inside that cell using the HTML symbols.

If the cell does not start/end with the above tokens, then the cell is treated as plain text, and such symbols should get converted to the HTML equivalent for use in the export file.

**Comment by farling42** [comment]
The specific issue is that the ">" isn't getting converted into "&amp;gt;".
The "<" is correctly getting converted into "&amp;lt;"

I actually think that this is a bug in RW when it is parsing the import file.
